spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/bddfithub
    username: postgres
    password: abc123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

# Configuración para la API de Exercisedb
exercisedb:
  api-key: fe56d0d80amsh235f02a93340fbdp120fb7jsn3aeedaa46b85

