### crear objetivo de tipo levantar peso o repetición
POST http://localhost:8080/api/v1/goal/create
Content-Type: application/json
Accept: application/json

{
    "quantity": 12,
    "userId": 1,
    "typeGoal": 1,
    "exerciseName": "air bike"
}

### crear objetivo de tipo bajar de peso

POST http://localhost:8080/api/v1/goal/create
Content-Type: application/json
Accept: application/json

{
    "quantity": 0,
    "userId": 1,
    "typeGoal": 3
}

